//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PotatoCornerSys
{
    public partial class DatabaseBackup
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnBackup;
        protected global::System.Web.UI.WebControls.Label lblBackupMessage;
        protected global::System.Web.UI.WebControls.Button btnExportOrders;
        protected global::System.Web.UI.WebControls.Button btnExportUsers;
        protected global::System.Web.UI.WebControls.Label lblExportMessage;
        protected global::System.Web.UI.WebControls.FileUpload fileRestore;
        protected global::System.Web.UI.WebControls.Button btnRestore;
        protected global::System.Web.UI.WebControls.Label lblRestoreMessage;
        protected global::System.Web.UI.WebControls.Literal litBackupHistory;
    }
}